-- MySQL Script generated by MySQL Workbench
-- 12/31/14 12:19:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TEdASCoreDev
-- -----------------------------------------------------
-- Development DB for project TEd@S
-- -----------------------------------------------------
-- Schema TEdASUserDEV
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TEdASUserDEV` ;

-- -----------------------------------------------------
-- Schema TEdASUserDEV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TEdASUserDEV` ;
USE `TEdASUserDEV` ;

-- -----------------------------------------------------
-- Table `TEdASUserDEV`.`TB_UserRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEdASUserDEV`.`TB_UserRole` ;

CREATE TABLE IF NOT EXISTS `TEdASUserDEV`.`TB_UserRole` (
  `RoleID` INT NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleID`, `Role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEdASUserDEV`.`TB_UserLogin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEdASUserDEV`.`TB_UserLogin` ;

CREATE TABLE IF NOT EXISTS `TEdASUserDEV`.`TB_UserLogin` (
  `UserID` INT NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `UserPass` VARCHAR(512) NOT NULL,
  `UserRole` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`UserID`, `UserName`, `UserPass`),
  INDEX `FK_User_role_idx` (`UserRole` ASC),
  CONSTRAINT `FK_User_role`
    FOREIGN KEY (`UserRole`)
    REFERENCES `TEdASUserDEV`.`TB_UserRole` (`RoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEdASUserDEV`.`TB_LoginSuccessLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEdASUserDEV`.`TB_LoginSuccessLog` ;

CREATE TABLE IF NOT EXISTS `TEdASUserDEV`.`TB_LoginSuccessLog` (
  `UserID` INT NOT NULL,
  `LoginTime` VARCHAR(45) NOT NULL,
  CONSTRAINT `FK_UserID`
    FOREIGN KEY ()
    REFERENCES `TEdASUserDEV`.`TB_UserLogin` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEdASUserDEV`.`TB_LoginFailLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEdASUserDEV`.`TB_LoginFailLog` ;

CREATE TABLE IF NOT EXISTS `TEdASUserDEV`.`TB_LoginFailLog` (
  `UserName` INT NULL,
  `UserPass` VARCHAR(45) NULL,
  `LoginTime` VARCHAR(45) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
