/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-02-28 15:51:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/head.jsp", Long.valueOf(1424742902204L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Tead@s</title>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("    \r\n");
      out.write("         <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("      \r\n");
      out.write("         <script src=\"CSS/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"jq/jquery-ui.min.js\"></script>\r\n");
      out.write("     <script src=\"CSS/bootbox.js\"></script>\r\n");
      out.write("    <script src=\"jq/form-validator/jquery.form-validator.min.js\"></script>\r\n");
      out.write("          <script type=\"text/javascript\" charset=\"utf8\" src=\"CSS/DataTables-1.10.4/media/js/jquery.dataTables.js\"></script>\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/DataTables-1.10.4/media/css/jquery.dataTables.css\">\r\n");
      out.write("        \r\n");
      out.write("     <link href=\"CSS/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"CSS/main.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"jq/jquery-ui.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<title>TEAd@S</title>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("  <header>\r\n");
      out.write("      <img class=\"logo\" src=\"Images\\logo_orange.png\" alt=\"TEAd@S\">\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\" style=\"width:488px;margin: 0 auto\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>Welcome to Teadas User Login</h1>\r\n");
      out.write("<p>Please enter your user credentials below</p>\r\n");
      out.write("<form class=\"form\" action=\"LoginUser\" method=\"post\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("Username: <input type=\"text\" name=\"user\">\r\n");
      out.write("</div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("Password: <input type=\"password\" name=\"pwd\">\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"submit\" value=\"Login\">\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
