/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-01-14 07:46:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("    <script src=\"js/jquery-2.1.0.min.js\"></script>\r\n");
      out.write("         <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("         <script type='text/javascript' src=\"UserLogin.js\"></script>\r\n");
      out.write("    <script type='text/javascript'>\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function(){$('#LoginButton').click(function()\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \talert(\"button pressed\");\r\n");
      out.write("    \r\n");
      out.write("    \t loginuser();\r\n");
      out.write("    \t\r\n");
      out.write("    \r\n");
      out.write("    \t\t\r\n");
      out.write("    \t//alert(user_data + \"main\");\r\n");
      out.write("        //userLog();\r\n");
      out.write("    \t\t});\r\n");
      out.write("  \r\n");
      out.write("    \t\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("<title>TEAd@S</title>\r\n");
      out.write("  <link href=\"CSS\\bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"CSS\\main.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body id=\"myBod1\">\r\n");
      out.write("   <header>\r\n");
      out.write("        <img class=\"logo\" src=\"Images\\logo_orange.png\" alt=\"TEAd@S\">\r\n");
      out.write("    </header>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div id=\"alertmessage\"></div>\r\n");
      out.write("\t<h1 class=\"h\">\r\n");
      out.write("     \r\n");
      out.write("    </h1>\r\n");
      out.write("    \r\n");
      out.write("<form id=\"Userform\" class=\"form-horizontal\">\r\n");
      out.write("<fieldset>\r\n");
      out.write("\r\n");
      out.write("<!-- Form Name -->\r\n");
      out.write("<legend>Login</legend>\r\n");
      out.write("\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"control-group\">\r\n");
      out.write("  <label class=\"control-label\" for=\"user\">User Name</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <input id=\"user\" name=\"user\" placeholder=\"User Name\" class=\"input-large\" required=\"This is required\" type=\"text\">\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"control-group\">\r\n");
      out.write("  <label class=\"control-label\" for=\"pwd\">Password</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <input id=\"pwd\" name=\"pwd\" placeholder=\"Password\" class=\"input-large\" required=\"This is required\" type=\"text\">\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Button -->\r\n");
      out.write("\r\n");
      out.write("  <div>\r\n");
      out.write("    <button id=\"LoginButton\" class=\"btn btn-primary\">Login</button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<div id='content'></div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
